# Generated by Django 3.1.1 on 2020-10-23 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_input_chklst', '0007_auto_20201016_1031'),
        ('app_user', '0012_auto_20201015_1555'),
        ('app_create_chklst', '0006_auto_20201010_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckListDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cld_status', models.PositiveSmallIntegerField(default=0, verbose_name='Status')),
                ('cld_key', models.CharField(max_length=15, verbose_name='Key')),
                ('cld_mail_sent', models.BooleanField(default=False, verbose_name='Mail sent')),
                ('cld_pdf_file', models.FileField(upload_to='checklists/%Y/%m/', verbose_name='PDF Filename')),
                ('cld_mat', models.CharField(max_length=30, null=True, verbose_name='Material')),
                ('cld_man', models.CharField(max_length=30, null=True, verbose_name='Manager')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('cld_checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cld_checklist', to='app_create_chklst.checklist')),
                ('cld_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cld_company', to='app_user.company')),
                ('cld_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cld_manager', to='app_input_chklst.manager')),
                ('cld_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cld_material', to='app_input_chklst.material')),
                ('cld_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cld_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Check-List Done',
                'verbose_name_plural': 'Check-Lists Done',
                'ordering': ['cld_company', 'cld_key'],
            },
        ),
        migrations.AddIndex(
            model_name='checklistdone',
            index=models.Index(fields=['cld_company'], name='I_cld_Company'),
        ),
        migrations.AddConstraint(
            model_name='checklistdone',
            constraint=models.UniqueConstraint(fields=('cld_key', 'cld_company'), name='Unique key/society'),
        ),
    ]
