# Generated by Django 3.1.1 on 2020-10-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checklist', '0002_auto_20201023_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistphoto',
            name='pho_file',
            field=models.ImageField(upload_to='photos/%Y/%m/', verbose_name='Photo'),
        ),
    ]
