# Generated by Django 3.1.1 on 2020-10-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checklist', '0003_auto_20201026_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdone',
            name='cld_key',
            field=models.CharField(max_length=15, null=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='checklistdone',
            name='cld_pdf_file',
            field=models.FileField(null=True, upload_to='checklists/%Y/%m/', verbose_name='PDF Filename'),
        ),
    ]
