# Generated by Django 3.1.2 on 2020-11-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checklist', '0004_auto_20201026_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdone',
            name='cld_key',
            field=models.CharField(default='1604249087.2158', max_length=15, null=True, verbose_name='Key'),
        ),
    ]
