# Generated by Django 3.1.2 on 2020-11-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checklist', '0005_auto_20201101_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdone',
            name='cld_key',
            field=models.CharField(default='1604353911.0053', max_length=15, null=True, verbose_name='Key'),
        ),
    ]
