# Generated by Django 3.1.2 on 2020-11-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checklist', '0006_auto_20201102_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdone',
            name='cld_key',
            field=models.CharField(default='1605083512.6587', max_length=15, null=True, verbose_name='Key'),
        ),
    ]
