# Generated by Django 3.1.2 on 2020-11-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checklist', '0007_auto_20201111_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdone',
            name='cld_key',
            field=models.CharField(default='1605536125.4370', max_length=15, null=True, verbose_name='Key'),
        ),
    ]
