# Generated by Django 3.1.2 on 2020-11-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checklist', '0008_auto_20201116_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdone',
            name='cld_key',
            field=models.CharField(default='1605537580.6086', max_length=15, null=True, verbose_name='Key'),
        ),
    ]
