# Generated by Django 3.1.2 on 2020-11-16 14:46

import app_checklist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checklist', '0010_auto_20201116_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdone',
            name='cld_key',
            field=models.CharField(default=app_checklist.models.cld_default_id, max_length=15, null=True, verbose_name='Key'),
        ),
    ]
