# Generated by Django 3.1.1 on 2020-10-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0011_auto_20201002_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mgr_name', models.CharField(max_length=30, verbose_name='Owner')),
                ('mgr_contact', models.CharField(blank=True, max_length=30, null=True, verbose_name='Contact')),
                ('mgr_phone', models.CharField(blank=True, max_length=31, null=True, verbose_name='Phone')),
                ('mgr_email1', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email1')),
                ('mgr_email2', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email2')),
                ('mgr_enable', models.BooleanField(default=True, verbose_name='Enable')),
                ('mgr_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mgr_address', to='app_user.address')),
                ('mgr_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mgr_company', to='app_user.company')),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
                'ordering': ['mgr_company', 'mgr_name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_designation', models.CharField(max_length=30, verbose_name='Naming')),
                ('mat_registration', models.CharField(blank=True, max_length=30, null=True, verbose_name='Serial')),
                ('mat_Type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Type')),
                ('mat_model', models.CharField(blank=True, max_length=30, null=True, verbose_name='Model')),
                ('mat_enable', models.BooleanField(default=True, verbose_name='Enable')),
                ('mat_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mat_manager', to='app_input_chklst.manager')),
                ('mat_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mat_secondary', to='app_input_chklst.material')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['mat_manager', 'mat_designation'],
            },
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['mat_manager'], name='I_Mat_Manager'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('mat_registration', 'mat_manager'), name='Unique materiel/manager'),
        ),
        migrations.AddIndex(
            model_name='manager',
            index=models.Index(fields=['mgr_company'], name='I_Mgr_Company'),
        ),
        migrations.AddConstraint(
            model_name='manager',
            constraint=models.UniqueConstraint(fields=('mgr_name', 'mgr_company'), name='Unique mgr/society'),
        ),
    ]
