# Generated by Django 3.1.1 on 2020-10-15 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_input_chklst', '0004_auto_20201015_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='mat_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mat_manager', to='app_input_chklst.manager'),
        ),
        migrations.AlterField(
            model_name='material',
            name='mat_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mat_secondary', to='app_input_chklst.material'),
        ),
    ]
