# Generated by Django 3.1.1 on 2020-10-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_input_chklst', '0006_material_mat_company'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='material',
            name='Unique materiel/manager',
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('mat_designation', 'mat_manager'), name='Unique materiel/manager'),
        ),
    ]
