# Generated by Django 3.1.1 on 2020-09-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(max_length=100, unique=True, verbose_name='Field Position')),
                ('FR', models.TextField(verbose_name='French Text')),
                ('UK', models.TextField(verbose_name='English Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['Position'],
            },
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['Position'], name='I_Position'),
        ),
    ]
