# Generated by Django 3.1.1 on 2020-09-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.PositiveSmallIntegerField(default=0, verbose_name='Street Number')),
                ('street_type', models.CharField(blank=True, default='', max_length=20, verbose_name='Street Type')),
                ('address1', models.CharField(blank=True, default='', max_length=150, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, default='', max_length=150, verbose_name='Address 2')),
                ('zipcode', models.CharField(blank=True, default='', max_length=20, verbose_name='Zip Code')),
                ('city', models.CharField(blank=True, default='', max_length=50, verbose_name='City')),
                ('country', models.CharField(blank=True, default='', max_length=40, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['Position'], 'verbose_name': 'Translation'},
        ),
    ]
