# Generated by Django 3.1.1 on 2020-09-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utilities', '0002_auto_20200922_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Mnemonic address name'),
        ),
    ]
