# Generated by Django 3.1.1 on 2020-09-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utilities', '0003_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mnemonic address name'),
        ),
    ]
