# Generated by Django 3.1.1 on 2020-09-30 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_utilities', '0004_auto_20200930_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='name',
            new_name='address_name',
        ),
    ]
