# Generated by Django 3.1.1 on 2020-10-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0008_auto_20201002_1353'),
        ('app_utilities', '0006_auto_20201001_1553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
