# Generated by Django 3.1.1 on 2020-09-22 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_utilities', '0002_auto_20200922_2147'),
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLanguages',
            fields=[
                ('code', models.CharField(default='FR', max_length=2, primary_key=True, serialize=False, unique=True, verbose_name='Language code')),
                ('language', models.CharField(default='Francais', max_length=20, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'User Languages',
                'verbose_name_plural': 'User Languages',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Society')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='society', to='app_utilities.address', verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_language', to='app_user.userlanguages'),
        ),
    ]
