# Generated by Django 3.1.1 on 2020-09-22 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_auto_20200922_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_company', to='app_user.company'),
        ),
    ]
