# Generated by Django 3.1.1 on 2020-09-26 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_utilities', '0002_auto_20200922_2147'),
        ('app_user', '0004_auto_20200924_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='society', to='app_utilities.address', verbose_name='Address'),
        ),
    ]
