# Generated by Django 3.1.1 on 2020-09-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_auto_20200926_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pro',
            field=models.BooleanField(default=False, verbose_name='is pro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
