# Generated by Django 3.1.1 on 2020-10-03 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0011_auto_20201002_2313'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_key', models.CharField(max_length=30, verbose_name='Category key')),
                ('cat_wording', models.CharField(max_length=80, verbose_name='Category title')),
                ('cat_enable', models.BooleanField(default=True, verbose_name='Category enabled')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('cat_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app_user.company')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['cat_company', 'cat_key'],
            },
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chk_key', models.CharField(max_length=30, verbose_name='Check-List key')),
                ('chk_title', models.CharField(max_length=80, verbose_name='Check-List title')),
                ('chk_enable', models.BooleanField(verbose_name='Check-List enabled')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Check-List',
                'verbose_name_plural': 'Check-Lists',
                'ordering': ['chk_company', 'chk_key'],
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_key', models.CharField(max_length=30, verbose_name='Line key')),
                ('line_wording', models.CharField(max_length=80, verbose_name='Line title')),
                ('line_enable', models.BooleanField(default=True, verbose_name='Line enabled')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('line_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line', to='app_user.company')),
            ],
            options={
                'verbose_name': 'Line',
                'verbose_name_plural': 'Lines',
                'ordering': ['line_company', 'line_key'],
            },
        ),
        migrations.CreateModel(
            name='CheckListLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chk_line_position', models.PositiveSmallIntegerField(verbose_name='Line Position')),
                ('chk_line_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cll_categories', to='app_create_chklst.line')),
                ('chk_line_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cll_checklists', to='app_create_chklst.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='CheckListCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chk_cat_position', models.PositiveSmallIntegerField(verbose_name='Category Position')),
                ('chk_cat_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clc_categories', to='app_create_chklst.category')),
                ('chk_cat_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clc_checklists', to='app_create_chklst.checklist')),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='chk_category',
            field=models.ManyToManyField(blank=True, default=None, related_name='checklist', through='app_create_chklst.CheckListCategory', to='app_create_chklst.Category'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='chk_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ckecklist', to='app_user.company'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='chk_line',
            field=models.ManyToManyField(blank=True, default=None, related_name='checklist', through='app_create_chklst.CheckListLine', to='app_create_chklst.Line'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='chk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='line',
            index=models.Index(fields=['line_company'], name='I_Line_Company'),
        ),
        migrations.AddConstraint(
            model_name='line',
            constraint=models.UniqueConstraint(fields=('line_key', 'line_company'), name='Unique line/society'),
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['chk_company'], name='I_Chk_Company'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['cat_company'], name='I_Cat_Company'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('cat_key', 'cat_company'), name='Unique category/society'),
        ),
    ]
