# Generated by Django 3.1.1 on 2020-10-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_create_chklst', '0002_auto_20201005_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='line_type',
            field=models.CharField(choices=[('C', 'Choice'), ('T', 'Text')], default='C', max_length=1, verbose_name='Line Type'),
        ),
    ]
