# Generated by Django 3.1.1 on 2020-10-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_create_chklst', '0003_line_line_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistline',
            old_name='chk_line_category',
            new_name='chk_line_line',
        ),
    ]
