# Generated by Django 3.1.1 on 2020-10-08 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_create_chklst', '0004_auto_20201007_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistline',
            name='chk_line_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cll_lines', to='app_create_chklst.line'),
        ),
    ]
