# Generated by Django 3.1.1 on 2020-10-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_create_chklst', '0005_auto_20201008_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistcategory',
            options={'ordering': ['chk_cat_checklist']},
        ),
        migrations.AlterModelOptions(
            name='checklistline',
            options={'ordering': ['chk_line_checklist']},
        ),
        migrations.AddIndex(
            model_name='checklistcategory',
            index=models.Index(fields=['chk_cat_checklist'], name='I_CheckListCategory'),
        ),
        migrations.AddIndex(
            model_name='checklistline',
            index=models.Index(fields=['chk_line_checklist'], name='I_CheckListLine'),
        ),
    ]
